### ISSUE TITLE
Removal of repositories - plugins for Logseq

### ISSUE THREAD

**Issue by sparkles6452** [sethyuan/sethyuan#1]
Hi @sethyuan ,

Big fan of your work.

Noticed alot (almost all) of your plugins have been removed.

By all means, you are the creator and rule over this work as you'd like.

Was just wondering if this was intentional or by some Github-mishap.

Have an nice day.

**Comment by sethyuan** [comment]
Hi @sparkles6452 , I removed all my Logseq plugins because the Logseq community representative considered [Orca Note](https://github.com/sethyuan/orca-note) (a new outliner I wrote) a competition and did not want to allow any material of the competition in their channel. I agreed.

**Comment by sparkles6452** [comment]
Thanks for all your effort
